repos:
  - repo: local
    hooks:
      - id: poetry-check-toml
        name: poetry-check-toml
        entry: poetry
        language: system
        files: ^pyproject\.toml$
        pass_filenames: false
        args: [ "check" ]

      - id: lint
        name: linting
        entry: lint.sh
        language: script
        pass_filenames: false
        always_run: true

#      - id: requirements
#        name: requirements
#        entry: poetry
#        language: system
#        always_run: true
#        args: [ "export", ">", "requirements.txt" ]

#      - id: mypy
#        name: mypy
#        entry: poetry
#        language: system
#        types: [ python ]
#        args: [ "run", "mypy" ]
#
#      - id: pytest
#        name: pytest
#        entry: poetry
#        language: system
#        always_run: true
#        pass_filenames: false
#        args: [ "run", "pytest" ]